Repository OpenTracksApp/OpenTracks, pull requests merged in 2022-05, with the labels that each got.

#1211 Vertical accuracy: process and import/export.
  doc/opentracks-schema-1.0.xsd
  src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
  src/androidTest/java/de/dennisguse/opentracks/io/file/importer/TrackPointAssert.java
  src/androidTest/res/raw/csv_export.csv
  src/main/java/de/dennisguse/opentracks/data/CachedTrackPointsIndexes.java
  src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
  src/main/java/de/dennisguse/opentracks/data/CustomSQLiteOpenHelper.java
  src/main/java/de/dennisguse/opentracks/data/models/TrackPoint.java
  src/main/java/de/dennisguse/opentracks/data/tables/TrackPointsColumns.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/CSVTrackExporter.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java
  src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java
  src/main/java/de/dennisguse/opentracks/io/file/importer/GpxTrackImporter.java
  src/main/java/de/dennisguse/opentracks/io/file/importer/KmlTrackImporter.java
Labels: enhancement

#1216 Implement Public API stop
  README.md
  src/main/AndroidManifest.xml
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordingFragment.java
  src/main/java/de/dennisguse/opentracks/publicapi/AbstractAPIActivity.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
  src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
Labels: enhancement

#1218 Cleanup: use explicit preference identifiers for TrackFileFormat.
  src/androidTest/java/de/dennisguse/opentracks/data/ShareContentProviderTest.java
  src/androidTest/java/de/dennisguse/opentracks/settings/PreferencesUtilsTest.java
  src/main/java/de/dennisguse/opentracks/data/ShareContentProvider.java
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
  src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
  src/main/res/values/settings.xml
Labels: maintenance

#1226 Public API: respect post-workout export.
  src/main/java/de/dennisguse/opentracks/publicapi/StopRecording.java
Labels: bug

#1239 Export: filename template now distinguishes between {date} and {time}.
  src/androidTest/java/de/dennisguse/opentracks/io/file/TrackFilenameGeneratorTest.java
  src/main/java/de/dennisguse/opentracks/io/file/TrackFilenameGenerator.java
  src/main/res/values/settings.xml
Labels: enhancement

#1230 Refactor permission requests.
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/java/de/dennisguse/opentracks/sensors/BluetoothRemoteSensorManager.java
  src/main/java/de/dennisguse/opentracks/settings/bluetooth/BluetoothLeSensorPreference.java
  src/main/java/de/dennisguse/opentracks/util/PermissionUtils.java
Labels: bug

#1242 Bugfix: resume functionality was not starting recording.
  src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java
  src/main/java/de/dennisguse/opentracks/TrackStoppedActivity.java
Labels: bug

#1234 TrackRecordingService: remove pause functionality.
  src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java
  src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestRecording.java
  src/androidTest/java/de/dennisguse/opentracks/services/TrackRecordingServiceTestStateMachine.java
  src/main/java/de/dennisguse/opentracks/services/RecordingStatus.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingManager.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingService.java
  src/main/java/de/dennisguse/opentracks/services/TrackRecordingServiceConnection.java
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerListActivity.java
  src/main/res/values-ar/strings.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-b+es+419/strings.xml
  src/main/res/values-bg/strings.xml
  src/main/res/values-ca/strings.xml
  src/main/res/values-cs/strings.xml
  src/main/res/values-da/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-et/strings.xml
  src/main/res/values-eu/strings.xml
  src/main/res/values-fa/strings.xml
  src/main/res/values-fi/strings.xml
  src/main/res/values-fr-rCA/strings.xml
  src/main/res/values-fr-rCH/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-gl/strings.xml
  src/main/res/values-hi/strings.xml
  src/main/res/values-hr/strings.xml
  src/main/res/values-hu/strings.xml
  src/main/res/values-in/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-iw/strings.xml
  src/main/res/values-ja/strings.xml
  src/main/res/values-ko/strings.xml
  src/main/res/values-lt/strings.xml
  src/main/res/values-lv/strings.xml
  src/main/res/values-mo/strings.xml
  src/main/res/values-ms/strings.xml
  src/main/res/values-nb/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-pt-rPT/strings.xml
  src/main/res/values-pt/strings.xml
  src/main/res/values-ro/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-th/strings.xml
  src/main/res/values-tl/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-uk/strings.xml
  src/main/res/values-vi/strings.xml
  src/main/res/values-zh-rHK/strings.xml
  src/main/res/values-zh-rTW/strings.xml
  src/main/res/values-zh/strings.xml
  src/main/res/values/strings.xml
Labels: maintenance

#1248 Allow settings reset and import/export while recording
  src/main/java/de/dennisguse/opentracks/settings/MainSettingsFragment.java
  src/main/res/values-ar/strings.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-b+es+419/strings.xml
  src/main/res/values-bg/strings.xml
  src/main/res/values-ca/strings.xml
  src/main/res/values-cs/strings.xml
  src/main/res/values-da/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-et/strings.xml
  src/main/res/values-eu/strings.xml
  src/main/res/values-fa/strings.xml
  src/main/res/values-fi/strings.xml
  src/main/res/values-fr-rCA/strings.xml
  src/main/res/values-fr-rCH/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-gl/strings.xml
  src/main/res/values-hi/strings.xml
  src/main/res/values-hr/strings.xml
  src/main/res/values-hu/strings.xml
  src/main/res/values-in/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-iw/strings.xml
  src/main/res/values-ja/strings.xml
  src/main/res/values-ko/strings.xml
  src/main/res/values-lt/strings.xml
  src/main/res/values-lv/strings.xml
  src/main/res/values-mo/strings.xml
  src/main/res/values-ms/strings.xml
  src/main/res/values-nb/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-pt-rPT/strings.xml
  src/main/res/values-pt/strings.xml
  src/main/res/values-ro/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-th/strings.xml
  src/main/res/values-tl/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-uk/strings.xml
  src/main/res/values-vi/strings.xml
  src/main/res/values-zh-rHK/strings.xml
  src/main/res/values-zh-rTW/strings.xml
  src/main/res/values-zh/strings.xml
  src/main/res/values/strings.xml
Labels: maintenance

#1255 Bugfix: request permissions in TrackListActivity.
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
Labels: bug

#1261 Cleanup: removed unused translations.
  src/main/res/values-ar/strings.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-b+es+419/strings.xml
  src/main/res/values-bg/strings.xml
  src/main/res/values-ca/strings.xml
  src/main/res/values-cs/strings.xml
  src/main/res/values-da/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-et/strings.xml
  src/main/res/values-eu/strings.xml
  src/main/res/values-fa/strings.xml
  src/main/res/values-fi/strings.xml
  src/main/res/values-fr-rCA/strings.xml
  src/main/res/values-fr-rCH/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-gl/strings.xml
  src/main/res/values-hi/strings.xml
  src/main/res/values-hr/strings.xml
  src/main/res/values-hu/strings.xml
  src/main/res/values-in/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-iw/strings.xml
  src/main/res/values-ja/strings.xml
  src/main/res/values-ko/strings.xml
  src/main/res/values-lt/strings.xml
  src/main/res/values-lv/strings.xml
  src/main/res/values-mo/strings.xml
  src/main/res/values-ms/strings.xml
  src/main/res/values-nb/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-pt-rPT/strings.xml
  src/main/res/values-pt/strings.xml
  src/main/res/values-ro/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-th/strings.xml
  src/main/res/values-tl/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-uk/strings.xml
  src/main/res/values-vi/strings.xml
  src/main/res/values-zh-rHK/strings.xml
  src/main/res/values-zh-rTW/strings.xml
  src/main/res/values-zh/strings.xml
  src/main/res/values/strings.xml
Labels: maintenance

#1253 Add "show on map" format selection dialog
  src/main/AndroidManifest.xml
  src/main/java/de/dennisguse/opentracks/TrackListActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordedActivity.java
  src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
  src/main/java/de/dennisguse/opentracks/settings/ImportExportSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java
  src/main/java/de/dennisguse/opentracks/settings/UserInterfaceSettingsFragment.java
  src/main/java/de/dennisguse/opentracks/share/ShowOnMapProxyActivity.java
  src/main/java/de/dennisguse/opentracks/util/IntentDashboardUtils.java
  src/main/res/values/do_not_translate.xml
  src/main/res/values/settings.xml
  src/main/res/values/strings.xml
  src/main/res/xml/settings_user_interface.xml
Labels: enhancement
